services:
  - type: web
    name: futbol-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python futbol_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: 1833071130
      - key: PYTHON_VERSION
        value: 3.11.9
